### ISSUE TITLE
Install dependencies conflict

### ISSUE THREAD

**Issue by LeeJMorel** [Weaverse/weaverse#484]
**Describe the bug**
There is a conflict between the libraries used in the pilot theme

**To Reproduce**

1. On a clean PC open terminal and run the install script.

**Expected behavior**
It should be able to install without conflicting libraries.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Linux [Ubuntu] through windows wsl

**Additional context**
Bug report:
[2024-07-16T19_44_38_943Z-eresolve-report.txt](https://github.com/user-attachments/files/16255890/2024-07-16T19_44_38_943Z-eresolve-report.txt)

**Comment by hta218** [comment]
Hey @LeeJMorel 
Thanks for flagging this! We're working on it - fixing and updating dependencies in the Pilot repo and `@weaverse/*` packages to smooth out the setup for new Weaverse Hydrogen projects. 
A new version with these fixes is on the way. Hang tight for the update 🙏

**Comment by paul-phan** [comment]
Hello @LeeJMorel, we have updated our CLI to resolve the issue. Please give it another try!
